version: '3.4'

services:
  janniebot:
    image: janniebot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      BOT_TOKEN: replaceme
      NODE_ENV: production
